#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "parsimonious",
#   "pygls",
# ]
# ///

import bisect
import contextlib
from dataclasses import dataclass
from itertools import accumulate, chain
from typing import Sequence, TypeVar

import lsprotocol.types as L
from parsimonious.exceptions import ParsimoniousError
from parsimonious.grammar import rule_grammar
from parsimonious.nodes import Node, NodeVisitor
from pygls.lsp.server import LanguageServer

U = TypeVar("U")


Maybe = tuple[U] | tuple[()]


def maybe[U](v: U | None) -> Maybe[U]:
    """Turns an optional value into an for-loop friendly `Iterable`."""
    return () if v is None else (v,)


# NOTE: The `Point` and `Span` classes are needed because the PyGLS `Position` and
# `Range` classes are non-hashable, while Parsimony needs `Span`s as dictionary keys.


@dataclass(frozen=True, order=True)
class Point:
    line: int
    character: int

    @staticmethod
    def from_lsp(pos: L.Position):
        return Point(pos.line, pos.character)

    def to_lsp(self):
        return L.Position(self.line, self.character)


@dataclass(frozen=True)
class Span:
    start: Point
    end: Point

    def contains(self, point: Point) -> bool:
        return self.start <= point <= self.end

    def to_lsp(self) -> L.Range:
        return L.Range(self.start.to_lsp(), self.end.to_lsp())


@dataclass
class Token:
    start: Point
    length: int
    type: L.SemanticTokenTypes


class SemanticTokensEncoder:
    def __init__(self) -> None:
        self.last_line: int = 0
        self.last_start_char: int = 0
        self.tokens: list[Token] = []
        self.encoded: list[int] = []

    def emit(self, token: Token):
        self.tokens.append(token)

    def encode(self):
        self.last_line: int = 0
        self.last_start_char: int = 0
        self.tokens.sort(key=lambda token: token.start)
        self.encoded = []

        for token in self.tokens:
            delta_start_line = token.start.line - self.last_line

            # `delta_start_char` must be absolute if the current token is on a different
            # line than the last token.
            delta_start_char = (
                token.start.character
                if delta_start_line != 0
                else token.start.character - self.last_start_char
            )

            self.last_line = token.start.line
            self.last_start_char = token.start.character

            self.encoded.append(delta_start_line)
            self.encoded.append(delta_start_char)
            self.encoded.append(token.length)
            self.encoded.append(list(L.SemanticTokenTypes).index(token.type))
            # Token modifiers, not used, always 0
            self.encoded.append(0)


class Analyzer(NodeVisitor):
    def __init__(self) -> None:
        super().__init__()
        self.reset()

    def reset(self):
        self.labels: dict[str, Span] = {}
        self.refs: dict[Span, str] = {}
        self.analyzed = False
        self.tokens = SemanticTokensEncoder()
        return self

    def analyze(self, node: Node):
        self.source = node.full_text
        self.lines = node.full_text.splitlines(keepends=True)

        # When the source ends with a newline, `str.splitlines` does not preserve the
        # last empty line.
        if node.full_text.endswith("\n"):
            self.lines.append("")

        # Computes the character offset of the first character in each line, used for
        # conversions between 2D points and 1D offsets.
        self.line_offsets: list[int] = list(
            accumulate(chain([0], map(len, self.lines)))
        )

        self.visit(node)
        self.analyzed = True

    def definition(self, uri: str, pos: L.Position) -> Sequence[L.Location]:
        if not self.analyzed:
            return []

        return [
            L.Location(uri, self.labels[name].to_lsp())
            for name, _ in maybe(self.ref_at(pos))
        ]

    def references(self, uri: str, pos: L.Position) -> Sequence[L.Location]:
        if not self.analyzed:
            return []

        return [
            L.Location(uri, ref_span.to_lsp())
            for label_name, _ in maybe(self.label_at(pos))
            for ref_span, ref_name in self.refs.items()
            if label_name == ref_name
        ]

    def document_symbol(self) -> Sequence[L.DocumentSymbol]:
        if not self.analyzed:
            return []

        return [
            L.DocumentSymbol(label, L.SymbolKind.Constructor, range, range)
            for label, span in self.labels.items()
            if (range := span.to_lsp())
        ]

    def document_highlight(self, pos: L.Position) -> Sequence[L.DocumentHighlight]:
        if not self.analyzed:
            return []

        def to_highlight(span: Span, kind: L.DocumentHighlightKind):
            return L.DocumentHighlight(span.to_lsp(), kind)

        def highlight_spans():
            for label_name, label_span in maybe(self.label_at(pos)):
                yield to_highlight(label_span, L.DocumentHighlightKind.Write)
                yield from (
                    to_highlight(ref_span, L.DocumentHighlightKind.Read)
                    for ref_span, ref_name in self.refs.items()
                    if label_name == ref_name
                )

            for ref_name, ref_span in maybe(self.ref_at(pos)):
                yield to_highlight(ref_span, L.DocumentHighlightKind.Read)
                yield from (
                    to_highlight(label_span, L.DocumentHighlightKind.Write)
                    for label_name, label_span in self.labels.items()
                    if label_name == ref_name
                )

        return list(highlight_spans())

    def semantic_tokens(self) -> L.SemanticTokens:
        self.tokens.encode()
        return L.SemanticTokens(data=self.tokens.encoded)

    def prepare_rename(self, pos: L.Position) -> L.PrepareRenamePlaceholder | None:
        if not self.analyzed:
            return None

        for label_name, label_span in maybe(self.label_at(pos)):
            return L.PrepareRenamePlaceholder(label_span.to_lsp(), label_name)

        for ref_name, ref_span in maybe(self.ref_at(pos)):
            return L.PrepareRenamePlaceholder(ref_span.to_lsp(), ref_name)

        return None

    def rename(self, uri: str, pos: L.Position, new_name: str) -> L.WorkspaceEdit:
        def text_edits():
            for name, label_span in maybe(self.label_at(pos)):
                yield L.TextEdit(label_span.to_lsp(), new_name)
                yield from (
                    L.TextEdit(ref_span.to_lsp(), new_name)
                    for ref_span, ref_name in self.refs.items()
                    if name == ref_name
                )

            for name, _ in maybe(self.ref_at(pos)):
                yield L.TextEdit(self.labels[name].to_lsp(), new_name)
                yield from (
                    L.TextEdit(ref_span.to_lsp(), new_name)
                    for ref_span, ref_name in self.refs.items()
                    if name == ref_name
                )

        return L.WorkspaceEdit(changes={uri: list(text_edits())})

    def label_at(self, pos: L.Position) -> tuple[str, Span] | None:
        return next(
            (
                (name, span)
                for name, span in self.labels.items()
                if span.contains(Point.from_lsp(pos))
            ),
            None,
        )

    def ref_at(self, pos: L.Position) -> tuple[str, Span] | None:
        return next(
            (
                (name, span)
                for span, name in self.refs.items()
                if span.contains(Point.from_lsp(pos))
            ),
            None,
        )

    def point_of(self, offset: int) -> Point:
        line = bisect.bisect_right(self.line_offsets, offset) - 1
        column = offset - self.line_offsets[line]
        return Point(line=line, character=column)

    def start_of(self, node: Node) -> Point:
        return self.point_of(node.start)

    def span_of(self, node: Node) -> Span:
        return Span(self.point_of(node.start), self.point_of(node.end))

    def emit_token(self, node: Node, type: L.SemanticTokenTypes):
        self.tokens.emit(Token(self.start_of(node), len(node.text), type))

    def generic_visit(self, node: Node, visited_children: Sequence[Node]):
        del visited_children
        return node

    def visit_comment(self, node: Node, _: Sequence[Node]):
        self.emit_token(node, L.SemanticTokenTypes.Comment)
        return node

    def visit_equals(self, node: Node, visited_children: Sequence[Node]):
        op, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        return node

    def visit_label(self, node: Node, visited_children: Sequence[Node]):
        del node
        label, *_ = visited_children
        return label

    def visit_lookahead(self, node: Node, visited_children: Sequence[Node]):
        op, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        return node

    def visit_not_term(self, node: Node, visited_children: Sequence[Node]):
        op, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        return node

    def visit_or_term(self, node: Node, visited_children: Sequence[Node]):
        op, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        return node

    def visit_parenthesized(self, node: Node, visited_children: Sequence[Node]):
        lparen, _, _, rparen, *_ = visited_children
        self.emit_token(lparen, L.SemanticTokenTypes.Operator)
        self.emit_token(rparen, L.SemanticTokenTypes.Operator)
        return node

    def visit_quantifier(self, node: Node, visited_children: Sequence[Node]):
        op, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        return node

    def visit_reference(self, node: Node, visited_children: Sequence[Node]):
        label, *_ = visited_children
        self.emit_token(label, L.SemanticTokenTypes.Variable)
        self.refs[self.span_of(label)] = label.text
        return node

    def visit_regex(self, node: Node, visited_children: Sequence[Node]):
        op, literal, *_ = visited_children
        self.emit_token(op, L.SemanticTokenTypes.Operator)
        self.emit_token(literal, L.SemanticTokenTypes.Regexp)
        return node

    def visit_rule(self, node: Node, visited_children: Sequence[Node]):
        label, _, _ = visited_children
        self.emit_token(label, L.SemanticTokenTypes.Function)
        self.labels[label.text] = self.span_of(label)
        return node

    def visit_spaceless_literal(self, node: Node, _: Sequence[Node]):
        self.emit_token(node, L.SemanticTokenTypes.String)
        return node


class ParsimonyServer(LanguageServer):
    analyzer: Analyzer = Analyzer()

    def info(self, message: str):
        self.window_show_message(L.ShowMessageParams(L.MessageType.Info, message))


server = ParsimonyServer(
    name="parsimony",
    version="v0.1",
    text_document_sync_kind=L.TextDocumentSyncKind.Full,
)


@server.feature(L.TEXT_DOCUMENT_DID_OPEN)
def did_open(ls: ParsimonyServer, params: L.DidOpenTextDocumentParams):
    with contextlib.suppress(ParsimoniousError):
        ls.analyzer.reset().analyze(rule_grammar.parse(params.text_document.text))


@server.feature(L.TEXT_DOCUMENT_DID_CHANGE)
def did_change(ls: ParsimonyServer, params: L.DidChangeTextDocumentParams):
    doc = ls.workspace.get_text_document(params.text_document.uri)
    with contextlib.suppress(ParsimoniousError):
        ls.analyzer.reset().analyze(rule_grammar.parse(doc.source))


@server.feature(L.TEXT_DOCUMENT_DEFINITION)
def definition(ls: ParsimonyServer, params: L.DefinitionParams):
    return ls.analyzer.definition(params.text_document.uri, params.position)


@server.feature(L.TEXT_DOCUMENT_REFERENCES)
def references(ls: ParsimonyServer, params: L.ReferenceParams):
    return ls.analyzer.references(params.text_document.uri, params.position)


@server.feature(L.TEXT_DOCUMENT_DOCUMENT_SYMBOL)
def document_symbol(ls: ParsimonyServer, _: L.DocumentSymbolParams):
    return ls.analyzer.document_symbol()


@server.feature(L.TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT)
def document_highlight(ls: ParsimonyServer, params: L.DocumentHighlightParams):
    return ls.analyzer.document_highlight(params.position)


@server.feature(L.TEXT_DOCUMENT_PREPARE_RENAME)
def prepare_rename(ls: ParsimonyServer, params: L.PrepareRenameParams):
    return ls.analyzer.prepare_rename(params.position)


@server.feature(L.TEXT_DOCUMENT_RENAME)
def rename(ls: ParsimonyServer, params: L.RenameParams):
    return ls.analyzer.rename(
        params.text_document.uri, params.position, params.new_name
    )


@server.feature(
    L.TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL,
    L.SemanticTokensLegend(
        token_types=list(L.SemanticTokenTypes),
        token_modifiers=[],
    ),
)
def semantic_tokens_full(ls: ParsimonyServer, _: L.SemanticTokensParams):
    return ls.analyzer.semantic_tokens()


if __name__ == "__main__":
    server.start_io()

# vim:ft=python
