#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "parsimonious",
#   "pygls",
# ]
# ///

import bisect
from dataclasses import dataclass
from itertools import accumulate, chain
from typing import Sequence, TypeVar, cast

import lsprotocol.types as L
from parsimonious.grammar import rule_grammar
from parsimonious.nodes import Node, NodeVisitor
from pygls.lsp.server import LanguageServer

U = TypeVar("U")


Maybe = tuple[U] | tuple[()]


def maybe[U](v: U | None) -> Maybe[U]:
    return () if v is None else (v,)


@dataclass(frozen=True, order=True)
class Point:
    line: int
    column: int

    def __str__(self) -> str:
        return f"{self.line}:{self.column}"

    @staticmethod
    def from_lsp(pos: L.Position):
        return Point(pos.line, pos.character)

    def to_lsp(self):
        return L.Position(self.line, self.column)


@dataclass(frozen=True)
class Span:
    start: Point
    end: Point

    def __str__(self) -> str:
        return f"{self.start}-{self.end}"

    def __contains__(self, point: Point) -> bool:
        return self.start <= point <= self.end

    def to_lsp(self) -> L.Range:
        return L.Range(self.start.to_lsp(), self.end.to_lsp())


@dataclass(frozen=True)
class Label:
    span: Span
    name: str


class Analyzer(NodeVisitor):
    def __init__(self) -> None:
        super().__init__()
        self.reset()

    def reset(self):
        self.labels: dict[str, Span] = {}
        self.refs: dict[Span, str] = {}
        self.ready = False

    def analyze(self, node: Node):
        self.source = node.full_text
        self.lines = node.full_text.splitlines(keepends=True)

        # When the source ends with a newline, `str.splitlines` does not preserve the
        # last empty line.
        if node.full_text.endswith("\n"):
            self.lines.append("")

        # Computes the character offset of the first character in each line, used for
        # converting 2D positions to 1D offsets.
        self.line_offsets: list[int] = list(
            accumulate(chain([0], map(len, self.lines)))
        )

        self.visit(node)
        self.ready = True

    def definition(self, uri: str, pos: L.Position) -> Sequence[L.Location]:
        return (
            []
            if not self.ready
            else [
                L.Location(uri, self.labels[name].to_lsp())
                for name, _ in maybe(self.ref_at(pos))
            ]
        )

    def references(self, uri: str, pos: L.Position) -> Sequence[L.Location]:
        return (
            []
            if not self.ready
            else [
                L.Location(uri, ref_span.to_lsp())
                for label_name, _ in maybe(self.label_at(pos))
                for ref_span, ref_name in self.refs.items()
                if label_name == ref_name
            ]
        )

    def document_symbol(self) -> Sequence[L.DocumentSymbol]:
        return [
            L.DocumentSymbol(label, L.SymbolKind.Class, range, range)
            for label, span in self.labels.items()
            if (range := span.to_lsp())
        ]

    def document_highlight(self, pos: L.Position):
        def to_highlight(span: Span, kind: L.DocumentHighlightKind):
            return L.DocumentHighlight(span.to_lsp(), kind)

        def highlight_spans():
            for label_name, label_span in maybe(self.label_at(pos)):
                yield to_highlight(label_span, L.DocumentHighlightKind.Write)
                yield from (
                    to_highlight(ref_span, L.DocumentHighlightKind.Read)
                    for ref_span, ref_name in self.refs.items()
                    if label_name == ref_name
                )

            for ref_name, ref_span in maybe(self.ref_at(pos)):
                yield to_highlight(ref_span, L.DocumentHighlightKind.Read)
                yield from (
                    to_highlight(label_span, L.DocumentHighlightKind.Write)
                    for label_name, label_span in self.labels.items()
                    if label_name == ref_name
                )

        return list(highlight_spans())

    def label_at(self, pos: L.Position) -> tuple[str, Span] | None:
        return next(
            (
                (name, span)
                for name, span in self.labels.items()
                if Point.from_lsp(pos) in span
            ),
            None,
        )

    def ref_at(self, pos: L.Position) -> tuple[str, Span] | None:
        return next(
            (
                (name, span)
                for span, name in self.refs.items()
                if Point.from_lsp(pos) in span
            ),
            None,
        )

    def point_of(self, offset: int) -> Point:
        line = bisect.bisect_right(self.line_offsets, offset) - 1
        column = offset - self.line_offsets[line]
        return Point(line=line, column=column)

    def span_of(self, start: int, end: int) -> Span:
        return Span(self.point_of(start), self.point_of(end))

    def generic_visit(self, node: Node, visited_children: Sequence[Node]):
        del visited_children
        return node

    def visit_label(self, node: Node, visited_children: Sequence[Node]):
        del node
        name, *_ = visited_children
        return Label(self.span_of(name.start, name.end), name.text)

    def visit_reference(self, node: Node, visited_children: Sequence[Node]):
        label, *_ = visited_children
        label = cast(Label, label)
        self.refs[label.span] = label.name
        return node

    def visit_rule(self, node: Node, visited_children: Sequence[Node]):
        label, _, _ = visited_children
        label = cast(Label, label)
        self.labels[label.name] = label.span
        return node


class ParsimonyServer(LanguageServer):
    analyzer: Analyzer = Analyzer()

    def info(self, message: str):
        self.window_show_message(L.ShowMessageParams(L.MessageType.Info, message))


server = ParsimonyServer(
    name="parsimony",
    version="v0.1",
    text_document_sync_kind=L.TextDocumentSyncKind.Full,
)


@server.feature(L.TEXT_DOCUMENT_DID_OPEN)
def did_open(ls: ParsimonyServer, params: L.DidOpenTextDocumentParams):
    ls.analyzer.reset()
    ls.analyzer.analyze(rule_grammar.parse(params.text_document.text))


@server.feature(L.TEXT_DOCUMENT_DID_CHANGE)
def did_change(ls: ParsimonyServer, params: L.DidChangeTextDocumentParams):
    doc = ls.workspace.get_text_document(params.text_document.uri)
    ls.analyzer.reset()
    ls.analyzer.analyze(rule_grammar.parse(doc.source))


@server.feature(L.TEXT_DOCUMENT_DEFINITION)
def definition(ls: ParsimonyServer, params: L.DefinitionParams):
    return ls.analyzer.definition(params.text_document.uri, params.position)


@server.feature(L.TEXT_DOCUMENT_REFERENCES)
def references(ls: ParsimonyServer, params: L.ReferenceParams):
    return ls.analyzer.references(params.text_document.uri, params.position)


@server.feature(L.TEXT_DOCUMENT_DOCUMENT_SYMBOL)
def document_symbol(ls: ParsimonyServer, _: L.DocumentSymbolParams):
    return ls.analyzer.document_symbol()


@server.feature(L.TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT)
def document_highlight(ls: ParsimonyServer, params: L.DocumentHighlightParams):
    return ls.analyzer.document_highlight(params.position)


if __name__ == "__main__":
    server.start_io()

# vim:ft=python
